apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eureka-service
  name: eureka-service
spec:
  ports:
  - name: 8761-8761
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: eureka-service
  type: ClusterIP
status:
  loadBalancer: {}
