apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eureka-service
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eureka-service
    spec:
      containers:
      - image: eureka-service:v1
        name: eureka-service
        resources: {}
status: {}
