apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: eureka-service
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eureka-service
    spec:
      containers:
      - image: gcr.io/ut-265822/eureka-service:v1
        name: eureka-service
        imagePullPolicy: Never
        ports:
          - containerPort: 8761
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka-service
  ports:
    - port: 8761
      protocol: TCP
      nodePort: 30089
  type: NodePort