version: '2.1'

services:
  eureka-server:
    image: gcr.io/ut-265822/eureka-service:v1
    container_name: eureka-server
  car-service:
    image: gcr.io/ut-265822/car-service:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  feign-car-service:
    image: gcr.io/ut-265822/feign-car-service:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  gateway-service:
    image: gcr.io/ut-265822/spring-gateway:v1
    container_name: gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080