version: '2'

services:
  eureka-service:
    image: gcr.io/ut-265822/eureka-service:v1
    container_name: eureka-server
    ports:
      - 8761:8761
  car-service:
    image: gcr.io/ut-265822/car-service:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8081:8081
  feign-car-service:
    image: gcr.io/ut-265822/feign-car-service:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8082:8082
  gateway-service:
    image: gcr.io/ut-265822/spring-gateway:v1
    container_name: gateway-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080