apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: micro2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: micro-services
    spec:
      containers:
        - name: eureka-service
          image: 'gcr.io/ut-265822/eureka-service:v1'
          ports:
            - containerPort: 8761
        - name: car-service
          image: 'gcr.io/ut-265822/car-service:v1'
        - name: feign-car-service
          image: 'gcr.io/ut-265822/feign-car-service:v1'
        - name: spring-gateway
          image: 'gcr.io/ut-265822/spring-gateway:v1'
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-gateway-service
  labels:
    name: spring-gateway-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-gateway
  type: LoadBalancer