apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: feign-car-service
  name: feign-car-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feign-car-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: feign-car-service
    spec:
      containers:
      - image: gcr.io/ut-265822/feign-car-service:v1
        name: feign-car-service
        imagePullPolicy: Never
        ports:
          - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 10
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: feign-car-service
spec:
  selector:
    app: feign-car-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      nodePort: 30086
  type: NodePort