apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-service
  name: eureka-service
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    app: eureka-service
status:
  loadBalancer: {}