apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-service
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  strategy: {}
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - image: gcr.io/ut-265822/eureka-service:v1
        imagePullPolicy: Never
        name: eureka-server
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
status: {}