apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-service
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  strategy: {}
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - env:
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes
        image: gcr.io/ut-265822/spring-gateway:v1
        imagePullPolicy: Never
        name: gateway-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}