apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: car-service
  name: car-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: car-service
    spec:
      containers:
      - image: car-service:v1
        name: car-service
        resources: {}
status: {}
