apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: car-service
  name: car-service
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: car-service
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: car-service
  name: car-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: car-service
    spec:
      containers:
      - image: car-service:v1
        name: car-service
        resources: {}
status: {}
