apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: car-service
  name: car-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: car-service
    spec:
      containers:
      - image: car-service
        name: car-service
        ports:
          - containerPort: 8081
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  selector:
    app: car-service
  ports:
    - port: 8081
      protocol: TCP
      nodePort: 30084
  type: NodePort