apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: car-service
  name: car-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-service
  strategy: {}
  template:
    metadata:
      labels:
        app: car-service
    spec:
      containers:
      - image: gcr.io/ut-265822/car-service:v1
        name: car-service
        ports:
          - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  type: NodePort
  selector:
    app: car-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30084