apiVersion: skaffold/v1
kind: Config
metadata:
  name: my-skaffold-car-service
#build:
#  artifacts:
#    - image: gcr.io/ut-265822/car-service
#      custom:
#        buildCommand: gradle bootBuildImage

deploy:
  kubectl:
    manifests:
      - deploy-app.yaml