apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-gateway
  name: spring-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-gateway
    spec:
      containers:
      - image: spring-gateway
        name: spring-gateway
        ports:
          - containerPort: 8080
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: spring-gateway
spec:
  selector:
    app: spring-gateway
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30085
  type: NodePort