apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-gateway
  name: spring-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-gateway
    spec:
      containers:
      - image: spring-gateway:v1
        name: spring-gateway
        resources: {}
status: {}
